#!/usr/bin/env bash

set -e

echo ">> waiting on kafka"
/container/wait-for-it/wait-for-it.sh --timeout=45 kafka:9092

echo ">> waiting on cassandra"
/container/wait-for-it/wait-for-it.sh --timeout=45 cassandra:9042

# typically cassandra needs a little more time to actually be ready 
sleep 3

echo ">> running ingester"
vulcan ingester
