#!/usr/bin/env bash

set -e

echo ">> waiting on kafka"
/container/wait-for-it/wait-for-it.sh --timeout=45 kafka:9092

echo ">> waiting on elasticsearch"
/container/wait-for-it/wait-for-it.sh --timeout=45 elasticsearch:9200

echo ">> running indexer"
vulcan indexer
