---
version: '2'
services:  
  zookeeper:
    image: jplock/zookeeper:3.4.8

  kafka:
    image: ches/kafka:0.10.0.0
    links:
    - zookeeper:zookeeper
    environment:
      ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

  cassandra:
    image: cassandra:2.2.7

  elasticsearch:
    image: elasticsearch:2.3.4

  node_exporter:
    image: prom/node-exporter:0.12.0
    command:
      - -collectors.enabled=diskstats,filesystem,loadavg,meminfo,netdev,stat,time,uname

  grafana:
    build:
      context: .
      dockerfile: grafana.dockerfile
    ports:
      - '3000:3000'
    links:
      - querier:querier
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SESSION_PROVIDER: memory
      GF_DASHBOARDS_JSON_ENABLED: 'true'
      GF_DASHBOARDS_JSON_PATH: /container/grafana/dashboards
    volumes:
      - ./container:/container:ro
    entrypoint: ['/container/grafana/run']

  scraper:
    build:
      context: ..
      dockerfile: dev/vulcan.dockerfile
    volumes:
      - ./container:/container:ro      
    entrypoint: ['/container/scraper/run']
    links:
    - node_exporter:node_exporter
    - kafka:kafka
    - zookeeper:zookeeper
    environment:
      VULCAN_ZK_SERVERS: zookeeper:2181
      VULCAN_KAFKA_ADDRS: kafka:9092

  indexer:
    build:
      context: ..
      dockerfile: dev/vulcan.dockerfile
    volumes:
      - ./container:/container:ro      
    entrypoint: ['/container/indexer/run']
    links:
    - node_exporter:node_exporter
    - kafka:kafka
    - zookeeper:zookeeper
    environment:
      VULCAN_KAFKA_ADDRS: kafka:9092
      VULCAN_ES: http://elasticsearch:9200/
      VULCAN_ES_SNIFF: 'false'

  ingester:
    build:
      context: ..
      dockerfile: dev/vulcan.dockerfile
    volumes:
      - ./container:/container:ro      
    entrypoint: ['/container/ingester/run']
    links:
    - node_exporter:node_exporter
    - kafka:kafka
    - zookeeper:zookeeper
    environment:
      VULCAN_CASSANDRA_ADDRS: cassandra
      VULCAN_KAFKA_ADDRS: kafka:9092

  querier:
    build:
      context: ..
      dockerfile: dev/vulcan.dockerfile
    volumes:
      - ./container:/container:ro
    ports:
      - '9090:9090'  
    entrypoint: ['/container/querier/run']
    links:
    - node_exporter:node_exporter
    - kafka:kafka
    - zookeeper:zookeeper
    environment:
      VULCAN_CASSANDRA_ADDRS: cassandra
      VULCAN_ES: http://elasticsearch:9200/
      VULCAN_ES_SNIFF: 'false'
