#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo ">> starting cluster"
docker-compose up -d

echo ">> waiting for querier to be online"
$DIR/container/wait-for-it/wait-for-it.sh $(docker-machine ip):9090 -t 45

open "http://$(docker-machine ip):3000/dashboard/file/node_exporter.json"
