// Code generated by protoc-gen-go.
// source: indexer.proto
// DO NOT EDIT!

/*
Package indexer is a generated protocol buffer package.

It is generated from these files:
	indexer.proto

It has these top-level messages:
	ResolveRequest
	ResolveResponse
	Matcher
	ValuesRequest
	ValuesResponse
*/
package indexer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MatcherType int32

const (
	MatcherType_Equal        MatcherType = 0
	MatcherType_NotEqual     MatcherType = 1
	MatcherType_RegexMatch   MatcherType = 2
	MatcherType_RegexNoMatch MatcherType = 3
)

var MatcherType_name = map[int32]string{
	0: "Equal",
	1: "NotEqual",
	2: "RegexMatch",
	3: "RegexNoMatch",
}
var MatcherType_value = map[string]int32{
	"Equal":        0,
	"NotEqual":     1,
	"RegexMatch":   2,
	"RegexNoMatch": 3,
}

func (x MatcherType) String() string {
	return proto.EnumName(MatcherType_name, int32(x))
}
func (MatcherType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResolveRequest struct {
	Matchers []*Matcher `protobuf:"bytes,1,rep,name=matchers" json:"matchers,omitempty"`
}

func (m *ResolveRequest) Reset()                    { *m = ResolveRequest{} }
func (m *ResolveRequest) String() string            { return proto.CompactTextString(m) }
func (*ResolveRequest) ProtoMessage()               {}
func (*ResolveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResolveRequest) GetMatchers() []*Matcher {
	if m != nil {
		return m.Matchers
	}
	return nil
}

type ResolveResponse struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *ResolveResponse) Reset()                    { *m = ResolveResponse{} }
func (m *ResolveResponse) String() string            { return proto.CompactTextString(m) }
func (*ResolveResponse) ProtoMessage()               {}
func (*ResolveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResolveResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Matcher struct {
	Type  MatcherType `protobuf:"varint,1,opt,name=type,enum=indexer.MatcherType" json:"type,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Value string      `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Matcher) Reset()                    { *m = Matcher{} }
func (m *Matcher) String() string            { return proto.CompactTextString(m) }
func (*Matcher) ProtoMessage()               {}
func (*Matcher) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Matcher) GetType() MatcherType {
	if m != nil {
		return m.Type
	}
	return MatcherType_Equal
}

func (m *Matcher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Matcher) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ValuesRequest struct {
	Field string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
}

func (m *ValuesRequest) Reset()                    { *m = ValuesRequest{} }
func (m *ValuesRequest) String() string            { return proto.CompactTextString(m) }
func (*ValuesRequest) ProtoMessage()               {}
func (*ValuesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ValuesRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type ValuesResponse struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *ValuesResponse) Reset()                    { *m = ValuesResponse{} }
func (m *ValuesResponse) String() string            { return proto.CompactTextString(m) }
func (*ValuesResponse) ProtoMessage()               {}
func (*ValuesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ValuesResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*ResolveRequest)(nil), "indexer.ResolveRequest")
	proto.RegisterType((*ResolveResponse)(nil), "indexer.ResolveResponse")
	proto.RegisterType((*Matcher)(nil), "indexer.Matcher")
	proto.RegisterType((*ValuesRequest)(nil), "indexer.ValuesRequest")
	proto.RegisterType((*ValuesResponse)(nil), "indexer.ValuesResponse")
	proto.RegisterEnum("indexer.MatcherType", MatcherType_name, MatcherType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Resolver service

type ResolverClient interface {
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	Values(ctx context.Context, in *ValuesRequest, opts ...grpc.CallOption) (*ValuesResponse, error)
}

type resolverClient struct {
	cc *grpc.ClientConn
}

func NewResolverClient(cc *grpc.ClientConn) ResolverClient {
	return &resolverClient{cc}
}

func (c *resolverClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	out := new(ResolveResponse)
	err := grpc.Invoke(ctx, "/indexer.Resolver/Resolve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) Values(ctx context.Context, in *ValuesRequest, opts ...grpc.CallOption) (*ValuesResponse, error) {
	out := new(ValuesResponse)
	err := grpc.Invoke(ctx, "/indexer.Resolver/Values", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Resolver service

type ResolverServer interface {
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	Values(context.Context, *ValuesRequest) (*ValuesResponse, error)
}

func RegisterResolverServer(s *grpc.Server, srv ResolverServer) {
	s.RegisterService(&_Resolver_serviceDesc, srv)
}

func _Resolver_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indexer.Resolver/Resolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_Values_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).Values(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indexer.Resolver/Values",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).Values(ctx, req.(*ValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Resolver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "indexer.Resolver",
	HandlerType: (*ResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _Resolver_Resolve_Handler,
		},
		{
			MethodName: "Values",
			Handler:    _Resolver_Values_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indexer.proto",
}

func init() { proto.RegisterFile("indexer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x51, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x65, 0x29, 0x5f, 0x1d, 0xa0, 0x36, 0x13, 0x02, 0x0d, 0x27, 0xb2, 0xc6, 0xa4, 0x31, 0x86,
	0x03, 0x1e, 0x4d, 0xb8, 0x99, 0x78, 0x91, 0xc3, 0xc6, 0x78, 0xf3, 0x50, 0xed, 0xa8, 0x4d, 0x4a,
	0xb7, 0x74, 0x5b, 0x02, 0xbf, 0xc0, 0xbf, 0x6d, 0xd8, 0xdd, 0x36, 0x22, 0xb7, 0xf7, 0x66, 0xdf,
	0x9b, 0xbe, 0x37, 0x85, 0x71, 0x92, 0xc5, 0x74, 0xa0, 0x62, 0x99, 0x17, 0xb2, 0x94, 0xd8, 0xb7,
	0x94, 0xaf, 0xc1, 0x13, 0xa4, 0x64, 0xba, 0x27, 0x41, 0xbb, 0x8a, 0x54, 0x89, 0x77, 0x30, 0xd8,
	0x46, 0xe5, 0xc7, 0x37, 0x15, 0x2a, 0x60, 0x0b, 0x27, 0x1c, 0xae, 0xfc, 0x65, 0x6d, 0x7e, 0x36,
	0x0f, 0xa2, 0x51, 0xf0, 0x6b, 0xb8, 0x6a, 0xfc, 0x2a, 0x97, 0x99, 0x22, 0xf4, 0xc1, 0x49, 0x62,
	0xe3, 0x75, 0xc5, 0x09, 0xf2, 0x37, 0xe8, 0x5b, 0x27, 0x86, 0xd0, 0x29, 0x8f, 0x39, 0x05, 0x6c,
	0xc1, 0x42, 0x6f, 0x35, 0xf9, 0xbf, 0xf9, 0xe5, 0x98, 0x93, 0xd0, 0x0a, 0x44, 0xe8, 0x64, 0xd1,
	0x96, 0x82, 0xf6, 0x82, 0x85, 0xae, 0xd0, 0x18, 0x27, 0xd0, 0xdd, 0x47, 0x69, 0x45, 0x81, 0xa3,
	0x87, 0x86, 0xf0, 0x1b, 0x18, 0xbf, 0x9e, 0x80, 0xaa, 0x2b, 0x4c, 0xa0, 0xfb, 0x99, 0x50, 0x1a,
	0xeb, 0xaf, 0xb8, 0xc2, 0x10, 0x1e, 0x82, 0x57, 0xcb, 0x6c, 0xd2, 0x29, 0xf4, 0xf4, 0x86, 0x3a,
	0xac, 0x65, 0xb7, 0x4f, 0x30, 0xfc, 0x93, 0x07, 0x5d, 0xe8, 0x3e, 0xee, 0xaa, 0x28, 0xf5, 0x5b,
	0x38, 0x82, 0xc1, 0x46, 0x96, 0x86, 0x31, 0xf4, 0x00, 0x04, 0x7d, 0xd1, 0x41, 0x8b, 0xfd, 0x36,
	0xfa, 0x30, 0xd2, 0x7c, 0x23, 0xcd, 0xc4, 0x59, 0xfd, 0x30, 0x18, 0xd8, 0xfb, 0x14, 0xb8, 0x86,
	0xbe, 0xc5, 0x38, 0x6b, 0x8a, 0x9f, 0x5f, 0x7f, 0x1e, 0x5c, 0x3e, 0x98, 0xb0, 0xbc, 0x85, 0x0f,
	0xd0, 0x33, 0x05, 0x70, 0xda, 0xa8, 0xce, 0x8a, 0xcf, 0x67, 0x17, 0xf3, 0xda, 0xfc, 0xde, 0xd3,
	0x3f, 0xfe, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x61, 0xf0, 0x41, 0x90, 0x09, 0x02, 0x00, 0x00,
}
