#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo ">> waiting on zk"
/container/wait-for-it/wait-for-it.sh --timeout=45 zookeeper:2181

echo ">> waiting on kafka"
/container/wait-for-it/wait-for-it.sh --timeout=45 kafka:9092

echo ">> setting sample-job"
vulcan job < $DIR/sample-job.yml

echo ">> running scraper"
vulcan scraper
