#!/bin/bash

set -ex

curl -fsSL https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz -o /tmp/glide.tar.gz
echo "0e2be5e863464610ebc420443ccfab15cdfdf1c4ab63b5eb25d1216900a75109  /tmp/glide.tar.gz" | sha256sum -c -
sudo tar -xf /tmp/glide.tar.gz --strip-components=1 -C /usr/local/bin/ linux-amd64/glide
rm /tmp/glide.tar.gz
